sensor_plugin:
  vo:
    vo_sub_topic_name: /zed/odom
    vo_noise_sigma: 0.001
    sensor_frame: zed_camera_center
    reference_frame: fc
    vio_flag: true # visual + imu odoemtry, means the odom frame is with respect to world, otherwise the odom frame will be with respect to the init camera frame for general visual only odometry
    valid_yaw: true # use the yaw angle from odometry for the flight control
    debug_verbose: false
    time_sync: true
    delay: -0.15
    variable_sensor_tf_flag: false
