sensor_plugin:
  vo:
    vo_sub_topic_name: /zed/odom
    level_pos_noise_sigma: 0.001 # use pos-vel-bias model, so need lower noise
    z_pos_noise_sigma: 0.01 #0.005
    vel_noise_sigma: 0.02
    sensor_frame: zed_camera_center
    reference_frame: fc
    debug_verbose: false
    time_sync: true
    delay: -0.15
    z_no_delay: true # special case of some vio algorithm such as zed mini
    variable_sensor_tf_flag: false
