sudo: required
dist: bionic
language: generic
env:
  - ROS_DISTRO=kinetic                 DOCKER_IMAGE=ubuntu:xenial
  - ROS_DISTRO=melodic                 DOCKER_IMAGE=ubuntu:bionic
  - ROS_DISTRO=noetic                  DOCKER_IMAGE=ubuntu:focal
matrix:
  allow_failures:
    - env: ROS_DISTRO=noetic                  DOCKER_IMAGE=ubuntu:focal
install:
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - docker run --rm -i -v $HOME:$HOME -e CI_SOURCE_PATH -e $REPOSITORY_NAME -e HOME -e DISTRO -e ROS_DISTRO -t $DOCKER_IMAGE bash -c 'cd $CI_SOURCE_PATH; source .travis.sh'
