### Fully actuated PID control for hydrusXI octo type

controller:
  need_yaw_d_control: false
  verbose: false
  torque_allocation_matrix_inv_pub_interval: 0.05
  wrench_allocation_matrix_pub_interval: 0.1

  alt:
    offset: 0.0
    limit: 12.0
    p_term_limit: 12.0
    i_term_limit: 12.0
    d_term_limit: 12.0
    alt_landing_const_i_ctrl_thresh: -0.2
    p_gain: 5.0
    i_gain: 0.4
    d_gain: 2.0
    takeoff_i_gain: 1.5

  xy:
    p_gain: 2.5
    i_gain: 0.05
    d_gain: 1.5
    limit: 10.0
    p_term_limit: 10.0
    i_term_limit: 10.0
    d_term_limit: 10.0
    x_offset: 0
    y_offset: 0
    start_rp_integration_height: 0.01

  yaw:
    limit: 10.0
    p_term_limit: 10.0
    i_term_limit: 10.0
    d_term_limit: 10.0
    p_gain: 2.0
    i_gain: 0.05
    d_gain: 4.0

  roll_pitch:
    limit: 10.0
    p_term_limit: 10.0
    i_term_limit: 10.0
    d_term_limit: 10.0
    p_gain: 5.0
    i_gain: 0.1
    d_gain: 10.0
