downward_camera_image_topic_name: /camera/image
downward_camera_info_topic_name: /camera/camera_info
imu_topic_name: /imu
odometry_topic_name: /hydrusx/ground_truth # /uav/baselink/odom CAUTION: the alt offset is not removed #

image_crop_scale: 0.7
max_count: 200

epipolar_thresh: 1
inlier_rate: 0.4

debug: false

camera_frame: downwards_cam_optical_frame
baselink_frame: fc