sensor_plugin:
        imu:
                imu_board: 1 #d_board
                imu_topic_name: /imu
                level_acc_noise_sigma: 0.06
                z_acc_noise_sigma: 0.05 #real:0.05
                acc_bias_noise_sigma: 0.001 #0.005#0.04
                angle_bias_noise_sigma: 0.0001 #good for EKF
                calib_time: 2.0

        gps: #single GPS
                min_est_sat_num: 7
                vel_noise_sigma:  0.05
                wp_ctrl_rate: 0
                frame_roll: 3.1415926

        altitude:
                barometer_sub_name: /baro
                baro_noise_sigma: 0.2
                baro_bias_noise_sigma: 0.001
                rx_freq: 80.0
                cutoff_freq: 10.0
                high_cutoff_freq: 1.0
