### Over-actuated PID control for hydrusXI octo type

# parameter for transform controller
controller/joint_state_sub_name: /hydrus_xi/joint_states
controller/verbose: true

# alt [m/s^2]
controller/alt/offset: 0.0
controller/alt/limit: 12.0 
controller/alt/p_term_limit: 12.0
controller/alt/i_term_limit: 12.0
controller/alt/d_term_limit: 12.0
controller/alt/alt_landing_const_i_ctrl_thresh: -0.2
controller/alt/p_gain: 5.0
controller/alt/i_gain: 0.3
controller/alt/d_gain: 20.0

# xy [m/s^2]
controller/xy/p_gain: 5.0
controller/xy/i_gain: 0.5
controller/xy/hovering_i_gain: 0.1
controller/xy/d_gain: 3.0
controller/xy/limit: 10.0
controller/xy/p_term_limit: 10.0 
controller/xy/i_term_limit: 10.0
controller/xy/d_term_limit: 10.0
controller/xy/x_offset: 0
controller/xy/y_offset: 0
controller/xy/xy_vel_weak_gain_sub_name: /velocity_control_gain_change

# yaw [rad/s^2]
controller/yaw/limit: 10.0
controller/yaw/p_term_limit: 10.0
controller/yaw/i_term_limit: 10.0
controller/yaw/d_term_limit: 10.0
controller/yaw/p_gain: 2.0
controller/yaw/i_gain: 0.05
controller/yaw/d_gain: 4.0

# roll&pitch [rad/s^2]
controller/roll_pitch/limit: 10.0
controller/roll_pitch/p_term_limit: 10.0
controller/roll_pitch/i_term_limit: 10.0
controller/roll_pitch/d_term_limit: 10.0
controller/roll_pitch/p_gain: 5.0
controller/roll_pitch/i_gain: 0.1
controller/roll_pitch/d_gain: 10.0