hydrusx:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  attitude_controller:
    type: flight_controllers/SimulationAttitudeController

  actuator_controller:
    joints:
      pid: {p: 50.0, i: 0.01, d: 2.0}
      init_value: 1.57
      type: effort_controllers/JointPositionController

      controller1:
        joint: joint1
        #type: effort_controllers/JointPositionController # you can specify for each controller
        #pid: {p: 50.0, i: 0.01, d: 2.0} # you can specify for each controller
        #init_value: 0  # you can specify for each controller
      controller2:
        joint: joint2
      controller3:
        joint: joint3
