bridge_rate: 50
joint_num: 5
bridge_mode: 1

# need to be ordered as the serial link
joint:
        "1":
                name: joint1
                angle_max: 1.58
                angle_min: -1.58
                angle_sgn: 1
                angle_scale: 0.001534
                angle_offset: 2046

        "2":
                name: joint2
                angle_max: 1.58
                angle_min: -1.58
                angle_sgn: 1
                angle_scale: 0.001534
                angle_offset: 2065

        "3":
                name: joint3
                angle_max: 1.58
                angle_min: -1.58
                angle_sgn: 1
                angle_scale: 0.001534
                angle_offset: 1921
