dragon:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  attitude_controller:
    type: flight_controllers/SimulationAttitudeController

  actuator_controller:
    joints:
      pid: {p: 50.0, i: 0.01, d: 2.0}
      init_value: 0
      type: effort_controllers/JointPositionController

      controller1:
        joint: joint1_pitch
        #type: effort_controllers/JointPositionController # you can specify for each controller
        #pid: {p: 50.0, i: 0.01, d: 2.0} # you can specify for each controller
      controller2:
        joint: joint1_yaw
        init_value: 1.57
      controller3:
        joint: joint2_pitch
      controller4:
        joint: joint2_yaw
        init_value: 1.57
      controller5:
        joint: joint3_pitch
      controller6:
        joint: joint3_yaw
        init_value: 1.57

    gimbals:
      pid: {p: 50.0, i: 0.01, d: 0.0}
      init_value: 0
      type: effort_controllers/JointPositionController

      controller1:
        joint: gimbal1_roll
      controller2:
        joint: gimbal1_pitch
      controller3:
        joint: gimbal2_roll
      controller4:
        joint: gimbal2_pitch
      controller5:
        joint: gimbal3_roll
      controller6:
        joint: gimbal3_pitch
      controller7:
        joint: gimbal4_roll
      controller8:
        joint: gimbal4_pitch

