<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="hydrusx_link" >

  <!-- D-H kai description(different from prof.nakamura) -->
  <xacro:macro name="hydrusx_link" params="self child rotor_direction general fc pc">

    <!-- link -->
    <link name="link${self}">
      <!-- common inertial -->
      <inertial>
        <origin xyz="${link_length* 0.5} 0 0" rpy="0 0 0"/>
        <mass value="${link_rod_mass + link_center_mass + protector_mass + protector_holder_mass - rotor_mass}" /> <!-- exclude from center mass -->
        <inertia
            ixx="${protector_inertia / 2}" ixy="0.0" ixz="0.0"
            iyy="${link_rod_inertia + protector_holder_inertia + protector_inertia /2}" iyz="0.0"
            izz="${link_rod_inertia + protector_holder_inertia + protector_inertia}"/>
      </inertial>

      <!-- sepcial inertia & visual & collision -->
      <!-- head -->
      <xacro:if value="${self == 1}">
        <xacro:link_model type="1" />
      </xacro:if>

      <!-- tail -->
      <xacro:if value="${self == child}">
        <xacro:link_model type="4" />
      </xacro:if>

      <!-- fc -->
      <xacro:if value="${fc}">
        <xacro:link_model type="3" />
      </xacro:if>

      <!-- pc: -->
      <xacro:if value="${pc}">
        <xacro:link_model type="2" />
      </xacro:if>

      <!-- general -->
      <xacro:if value="${general}">
        <xacro:link_model type="5" />
      </xacro:if>
    </link>
    <xacro:damping_factor link ="link${self}"/>

    <!-- rotor -->
    <joint name="rotor${self}" type="continuous">
      <limit effort="100.0" lower="0" upper="${max_force}" velocity="0.5"/> <!-- force range -->
      <parent link="link${self}"/>
      <child link="thrust${self}"/>
      <origin rpy="0 0 0" xyz="${link_length* 0.5} 0 0"/>
      <axis xyz="0 0 ${rotor_direction}"/>
    </joint>

    <link name="thrust${self}">
      <!-- visual & collisiont -->
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${rotor_mass}"/>
        <inertia
            ixx="${rotor_mass * .25 * rotor_radius * rotor_radius}" ixy="0.0" ixz="0.0"
            iyy="${rotor_mass * .25 * rotor_radius * rotor_radius}" iyz="0.0"
            izz="${rotor_mass * .5 * rotor_radius * rotor_radius}"/>
      </inertial>

      <collision>
        <origin rpy="0 0 0" xyz="0 0 -0.03"/>
        <geometry>
          <cylinder length="0.15" radius="${protector_radius + 0.01}"/>
        </geometry>
        </collision>

    </link>
    <xacro:damping_factor link ="thrust${self}"/>

    <!-- extra module -->
    <!-- head -->
    <xacro:if value="${self == 1}">
      <!-- dummy root link for KDL -->
      <link name="root">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.00001"/>
          <inertia
              ixx="0.000001" ixy="0.0" ixz="0.0"
              iyy="0.000001" iyz="0.0"
              izz="0.000002"/>
        </inertial>
      </link>
      <joint name="root_joint" type="fixed">
        <parent link="root"/>
        <child link="link${self}"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <axis xyz="0 0 1"/>
      </joint>

      <xacro:extra_module name = "head" parent = "${self}" mass = "${head_leg_mass}" >
        <origin xyz="${link_length * 0.5 + head_leg_offset} 0.0 0.0" rpy="0 0 0"/>
      </xacro:extra_module>

      <!-- battery -->
      <xacro:extra_module name = "bat${self}" parent = "${self}" mass = "${bat_mass}" >
        <origin xyz="${link_length * 0.5 + bat_offset} 0.0 0.0" rpy="0 0 0"/>
      </xacro:extra_module>

    </xacro:if>

    <!-- tail -->
    <xacro:if value="${self == child}">
      <xacro:extra_module name = "tail" parent = "${self}" mass = "${tail_leg_mass}" >
        <origin xyz="${link_length * 0.5 + tail_leg_offset} 0.0 0.0" rpy="0 0 0"/>
      </xacro:extra_module>

      <!-- battery -->
      <xacro:extra_module name = "bat${self}" parent = "${self}" mass = "${bat_mass}" >
        <origin xyz="${link_length * 0.5 + bat_offset} 0.0 0.0" rpy="0 0 0"/>
      </xacro:extra_module>
    </xacro:if>

    <!-- fc -->
    <xacro:if value="${fc}">
      <xacro:extra_module name = "fc" parent = "${self}" mass = "${fc_mass}" >
        <origin xyz="${link_length * 0.5 + fc_offset} 0.0 0.035" rpy="0 0 0"/>
      </xacro:extra_module>

      <!-- sensor for control -->
      <xacro:extra_module name = "sensor_c" parent = "${self}" mass = "${sensor_c_mass}" >
        <origin xyz="${link_length * 0.5 + sensor_c_offset} 0.0 0.0" rpy="0 0 0"/>
      </xacro:extra_module>

      <!-- battery -->
      <xacro:extra_module name = "bat${self}" parent = "${self}" mass = "${bat_mass}" >
        <origin xyz="${link_length * 0.5 + bat_offset} 0.0 0.0" rpy="0 0 0"/>
      </xacro:extra_module>
    </xacro:if>

    <!-- pc -->
    <xacro:if value="${pc}">
      <xacro:extra_module name = "pc_c" parent = "${self}" mass = "${pc_c_mass}" >
        <origin xyz="${link_length * 0.5 + pc_c_offset} 0.0 0.0" rpy="0 0 0"/>
      </xacro:extra_module>

      <!-- battery -->
      <xacro:extra_module name = "bat${self}" parent = "${self}" mass = "${bat_mass}" >
        <origin xyz="${link_length * 0.5 + bat_offset} 0.0 0.0" rpy="0 0 0"/>
      </xacro:extra_module>
    </xacro:if>

    <!-- general -->
    <xacro:if value="${general}">
      <!-- battery -->
      <xacro:extra_module name = "bat${self}" parent = "${self}" mass = "${bat_mass}" >
        <origin xyz="${link_length * 0.5 + bat_offset} 0.0 0.0" rpy="0 0 0"/>
      </xacro:extra_module>
    </xacro:if>

    <!-- joint -->>
    <xacro:unless value="${self == child}">
      <joint name="joint${self}" type="revolute">
        <limit effort="3.1" lower="-1.57" upper="1.57" velocity="0.5"/>
        <parent link="link${self}"/>
        <child link="link${child}"/>
        <origin rpy="0 0 0" xyz="${link_length} 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.8" friction="0.05"/>
      </joint>

      <xacro:extra_module name = "joint${self}_module" parent = "${self}" mass = "${joint_mass}" >
        <origin xyz="${link_length* 0.5 + link_joint_offset} 0.0 0.0" rpy="0 0 0"/>
      </xacro:extra_module>
    </xacro:unless>

    <!-- hardware interface -->
    <xacro:unless value="${self == child}">
      <transmission name="joint_tran${self}">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint${self}">
          <!-- TODO: effort is torque, maybe position is enough -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="servo{self}">
          <!-- TODO: effort is torque, maybe position is enough -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>
    </xacro:unless>

    <transmission name="rotor_tran${self}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="rotor${self}">
        <!-- TODO: effort is torque, maybe position is enough -->
        <hardwareInterface>RotorInterface</hardwareInterface>
      </joint>
      <actuator name="rotor${self}">
        <!-- TODO: effort is torque, maybe position is enough -->
        <hardwareInterface>RotorInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <xacro:friction self ="${self}"/>

  </xacro:macro>

</robot>
