<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="hydrus_xi_link">

  <xacro:macro name="hydrus_xi_link" params="self child rotor_direction link_type">

    <!-- link -->
    <link name="link${self}">
      <xacro:if value="${link_type == 'general'}">
        <inertial>
          <origin xyz="292.328082 -0.036798 13.019518" rpy="0 0 0"/>
          <mass value="0.592137"/>
          <inertia
              ixx="0.005358" iyy="0.023385" izz="0.027628"
              ixy="-0.000005" ixz="0.001913" iyz="0.000001"/>
        </inertial>
        <xacro:mesh_model type="link/general_link">
          <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:mesh_model>
        <xacro:link_collision_model/>
      </xacro:if>

      <xacro:if value="${link_type == 'head'}">
        <inertial>
          <origin xyz="325.815733 0.001640 0.712815" rpy="0 0 0"/>
          <mass value="0.517846"/>
          <inertia
              ixx="0.005427" iyy="0.020363" izz="0.024529"
              ixy="-0.000000" ixz="0.000311" iyz="-0.000000"/>
        </inertial>
        <xacro:mesh_model type="link/head_link">
          <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:mesh_model>
        <xacro:link_collision_model/>
      </xacro:if>

      <xacro:if value="${link_type == 'end'}">
        <inertial>
          <origin xyz="274.908603 -0.038527 12.973871" rpy="0 0 0"/>
          <mass value="0.565563"/>
          <inertia
              ixx="0.005345" iyy="0.018956" izz="0.023207"
              ixy="-0.000005" ixz="0.001804" iyz="0.000001"/>
        </inertial>
        <xacro:mesh_model type="link/end_link">
          <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:mesh_model>
        <xacro:link_collision_model/>
      </xacro:if>
    </link> <!-- link${self} -->
    <xacro:damping_factor link="link${self}"/>

    <!-- gimbal link -->
    <link name="gimbal_link${self}">
      <inertial>
        <origin xyz="-6.177736 0.000510 32.704127" rpy="0 0 0"/>
        <mass value="0.141889"/>
        <inertia
            ixx="0.000029" iyy="0.000027" izz="0.000031"
            ixy="0.000000" ixz="0.000002" iyz="-0.000000"/>
      </inertial>
      <xacro:mesh_model type="link/propeller_link">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:mesh_model>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${- collision_rotor_height / 2}"/>
        <geometry>
          <cylinder length="${collision_rotor_height}" radius="${protector_radius + 0.01}"/>
        </geometry>
      </collision>
    </link>
    <xacro:damping_factor link="gimbal_link${self}"/>

    <!-- thrust link (virtual) -->
    <link name="thrust${self}">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${rotor_mass}"/>
        <inertia
            ixx="${rotor_mass * .25 * rotor_radius * rotor_radius}" ixy="0.0" ixz="0.0"
            iyy="${rotor_mass * .25 * rotor_radius * rotor_radius}" iyz="0.0"
            izz="${rotor_mass * .5 * rotor_radius * rotor_radius}"/>
      </inertial>
    </link>
    <xacro:damping_factor link="thrust${self}"/>

    <!-- dummy root link for KDL -->
    <xacro:if value="${self == 1}">
      <link name="root">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.00001"/>
          <inertia
              ixx="0.000001" ixy="0.0" ixz="0.0"
              iyy="0.000001" iyz="0.0"
              izz="0.000002"/>
        </inertial>
      </link>
      <joint name="root_joint" type="fixed">
        <parent link="root"/>
        <child link="link${self}"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <axis xyz="0 0 1"/>
      </joint>
    </xacro:if>

    <!-- joints -->
    <!-- link joint -->
    <xacro:unless value="${self == child}">
      <joint name="joint${self}" type="revolute">
        <limit effort="3.3" lower="-1.57" upper="1.57" velocity="0.5"/>
        <parent link="link${self}"/>
        <child link="link${child}"/>
        <origin rpy="0 0 0" xyz="${link_length} 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.8" friction="0.05"/>
      </joint>
    </xacro:unless>

    <!-- gimbal joint -->
    <joint name="gimbal${self}" type="revolute">
      <limit effort="3.1" lower="-3.1415" upper="3.1415" velocity="0.5"/>
      <parent link="link${self}"/>
      <child link="gimbal_link${self}"/>
      <origin rpy="0 0 0" xyz="${link_length * 0.5} 0 0.05025"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.8" friction="0.05"/>
    </joint>

    <!-- rotor joint (virtual)-->
    <joint name="rotor${self}" type="continuous">
      <limit effort="100.0" lower="0" upper="${max_force}" velocity="0.5"/> <!-- force range -->
      <parent link="gimbal_link${self}"/>
      <child link="thrust${self}"/>
      <origin rpy="0 ${thrust_tilt_angle} 0" xyz="0.00249 0 0.05682"/>
      <axis xyz="0 0 ${rotor_direction}"/>
    </joint>

    <!-- hardware interface -->
    <xacro:unless value="${self == child}">
      <transmission name="joint_tran${self}">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint${self}">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="servo{self}">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>
    </xacro:unless>

    <transmission name="gimbal_tran${self}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="gimbal${self}">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="gimbal_servo{self}">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <transmission name="rotor_tran${self}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="rotor${self}">
        <hardwareInterface>RotorInterface</hardwareInterface>
      </joint>
      <actuator name="rotor${self}">
        <hardwareInterface>RotorInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <xacro:friction self ="${self}"/>

  </xacro:macro>
</robot>
