verbose: false

## old model
#downward_camera_image_topic_name: /zed/left/image_rect_color
#downward_camera_info_topic_name: /zed/left/camera_info
#imu_topic_name: /estimator/sensor_plugin/imu/imu_filtered
#odometry_topic_name: /uav/baselink/odom

downward_camera_image_topic_name: /camera/image
downward_camera_info_topic_name: /camera/camera_info
imu_topic_name: /estimator/sensor_plugin/imu/imu_filtered
odometry_topic_name: /uav/baselink/odom

image_crop_scale: 0.7
image_cut_pixel: 10
max_count: 100 #200
camera_roll_offset: 0  #-3.1415
camera_pitch_offset: 3.1415 # 0.0
camera_yaw_offset: 1.5708

use_sonar: false
sonar_offset: 0.0

epipolar_thresh: 0.5

debug: false

camera_frame: downwards_cam_optical_frame
